groups:
  - name: Alert register down
    rules:
      - alert: "On register down"
        expr: up{job="register-service"} < 1
        for: 10s
  - name: Alert auth down
    rules:
      - alert: "On auth down"
        expr: up{job="auth-service"} < 1
        for: 10s
