global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: 'mongodb'
    static_configs:
      - targets: ['db-exporter:27017']

  - job_name: 'register-service'
    static_configs:
      - targets: ['register-service:4000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:5000']


