version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/data/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command: --web.enable-lifecycle --config.file=/data/prometheus/prometheus.yml

  rabbitmq:
    image: rabbitmq:latest
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "5672:5672"

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root

  db-exporter:
    image: bitnami/mongodb-exporter:latest
    environment:
      - MONGODB_URI=mongodb://root:root@mongodb:27017
    depends_on:
      - mongodb

  register-service:
    build:
      context: ./register-service
      dockerfile: Dockerfile-RegisterService
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      REGISTERPORT: 4000
      JWT_SECRET_PARTICIPANT: participant
      JWT_SECRET_TARGETOWNER: targetowner
      REGISTER_MONGO_URL: mongodb://mongodb:27017/devops-register-service
      AMQP_URL: amqp://rabbitmq:5672

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile-AuthService
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      AUTHPORT: 3000
      JWT_SECRET_PARTICIPANT: participant
      JWT_SECRET_TARGETOWNER: targetowner
      AUTH_MONGO_URL: mongodb://mongodb:27017/devops-auth-service
      AMQP_URL: amqp://rabbitmq:5672

volumes:
  prometheus-data:
  mongodb_data: