version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "15672:15672"

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  register-service:
    build:
      context: ./register-service
      dockerfile: Dockerfile-RegisterService
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - rabbitmq
    env_file:
      .env

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile-AuthService
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - rabbitmq
    env_file:
      .env

volumes:
  mongodb_data: