name: Bunnyshell - Prepare Preview Environment Configuration
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - '*'
    paths-ignore:
      - "*.md"
  issue_comment:
    types: [ created, edited ]
jobs:
  deploy_prepare:
    name: Prepare Deployment of Environment
    uses: bunnyshell/workflows/.github/workflows/prepare-configuration.yaml@v2
    with:
      bunnyshell-yaml-path: .bunnyshell/bunnyshell.yaml
      allowed-users: "*"
      git-ref: refs/pull/${{ github.event.number || github.event.issue.number }}/head
      restricted-files: |
        .bunnyshell/*