name: lint-code-analyses

on:
  push:
    paths: [ 'Photo-prestiges/**' ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Photo-prestiges

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install ESLint and standard config
        run: npm install eslint eslint-config-standard --save-dev

      - name: Run ESLint
        run: npx eslint .
