name: lint-code-analyses

on:
  push:
    paths: [ 'Photo-prestiges/**' ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Photo-prestiges

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

